server:
  port: 8080
  servlet:
    context-path: /
spring:
  mvc:
    static-path-pattern: /static/**
  servlet:
    multipart:
      max-file-size: 10MB
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 20000
    lettuce:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
        max-wait: -1
cus:
  phonePrefix: /apps/phone_cube/data/mobilearea-1152.txt
  phonePath: /apps/phone_cube/data/area
  destPath: /apps/phone_cube/data/dest
logging:
  level:
    root: INFO
  path: ./logs
  file:
    max-history: 7
    max-size: 20MB