server:
  port: 12099
  servlet:
    context-path: /
spring:
  mvc:
    static-path-pattern: /static/**
  servlet:
    multipart:
      max-file-size: 10MB
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 20000
    lettuce:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
        max-wait: -1
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/phone_cube?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
      username: root
      password: jinchaoyang2019
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/cdr
mybatis:
  mapper-locations: classpath:mybatis/**/*.xml
  type-aliases-package: com.petbanny
  configuration:
    map-underscore-to-camel-case: true
cus:
  phonePrefix: /Users/jinchaoyang/Desktop/phone_cube/data/mobilearea-1152.txt
  phonePath: /Users/jinchaoyang/Desktop/phone_cube/data/area
  destPath: /Users/jinchaoyang/Desktop/phone_cube/data/dest
logging:
  level:
    root: INFO
  path: ./logs
  file:
    max-history: 1
    max-size: 20MB
asr:
  baidu: https://openapi.baidu.com/oauth/2.0/token